BBR-related fixes
signetlabdei/quic pull request #6
Opened 2020-05-18 12:08 UTC by il-theCrow

- `m_tcb` is no longer a `QuicSocketTxBuffer` attribute, it is now passed as arguments in methods requiring it (`RateSample` related)
- fixed order issues in retransmissions: lost stream frames are added after other text frames (FIFO Tx Scheduler only)
- fixed a problem for which retx frames were all sent in a single packet, exceeding the max allowed size and not following CC/pacing
- fixed a problem for which socket might not have enough data to transmit, causing app-limited `RateSample`s even with applications such as BulkSend

2020-05-18 15:03 UTC, mychele requested changes
Please check and fix the formatting of the code. I could not review a couple of files.

Besides, feel free to update the authors for the files you modified.

2020-05-18 15:03 UTC, mychele commented on README.md
> +This repository is a fork of [signetlabdei/quic](https://github.com/signetlabdei/quic) which contains in the code for a native IETF QUIC implementation in ns-3.
Rephrase

2020-05-18 15:03 UTC, mychele commented on README.md
> +BBR implementation for QUIC in ns-3
QUIC implementation for ns-3

2020-05-18 15:03 UTC, mychele commented on README.md
> +Please use this [issue tracker](https://github.com/il-theCrow/quic-ns-3/issues) for bugs/questions.
Move before ## BBR implementation

2020-05-18 15:03 UTC, mychele commented on README.md
> +git clone https://github.com/il-theCrow/quic quic
check

2020-05-18 15:03 UTC, mychele commented on model/quic-l4-protocol.cc
> +  socket->InitializeScheduling();
It seems that this PR also merges the scheduler code. Are we ok with this? @fedech

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +                   MakeBooleanChecker ())
Check indent

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +                   "LegacyCongestionControl",
same line?

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +	.AddAttribute ("CongControl",
Do not mix attributes and sources, place all the attributes before the sources

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +				   PointerValue (),
No default?

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +				   PointerValue (),
No default?

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +  NS_ASSERT (ok == true);
Maybe use an NS_ASSERT_MSG(ok == true, "message to explain the error");

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.cc
> +void QuicSocketBase::SetLatency(uint32_t streamId, Time latency) {
maybe run a check-style.py, these are not consistent with the ns-3 code style

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-base.h
> +	/**
Check indent (probably solved by check-style.py)

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-buffer.cc
> +	static TypeId tid =
fix indent and formatting

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-buffer.cc
> +}
fix indent and formatting

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-buffer.cc
>  #include "ns3/abort.h"
This file is very hard to review, formatting issues make it look completely different from the old one. Please check!

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-buffer.h
>  namespace ns3 {
Fix indent throughout

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-buffer.h
> +	uint32_t m_priorDelivered { 0 }; //!< The delivered count of the most recent packet delivered
{0};

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-edf-scheduler.cc
> +	static TypeId tid = TypeId("ns3::QuicSocketTxEdfScheduler").SetParent<
fix formatting

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-edf-scheduler.cc
> +/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
Indent and formatting throughout (check-style will probably be enough)

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-edf-scheduler.cc
> +Time QuicSocketTxEdfScheduler::GetLatency(uint32_t streamId) {
Get methods should be const

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-edf-scheduler.cc
> +	try {
do not use try/catch, use ns-3 asserts or aborts

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-edf-scheduler.h
> +	Time GetDefaultLatency();
const

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-pfifo-scheduler.cc
> + * Copyright (c) 2019 SIGNET Lab, Department of Information Engineering, University of Padova
Update

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-pfifo-scheduler.cc
> +/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
Fix formatting and indent

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-pfifo-scheduler.cc
> +void QuicSocketTxPFifoScheduler::Print(std::ostream &os) const {
Can this method be implemented in the base class?

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-scheduler.cc
> +/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
format, indent, copyright

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-scheduler.h
> +	~QuicSocketTxScheduler(void); /**
virtual

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-scheduler.h
> +	~QuicSocketTxScheduler(void); /**
and line break for the doxy of the other method

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-scheduler.h
> +	virtual void Print(std::ostream &os) const
You can make it a pure abstract function
`virtual void Print(std::ostream &os) const = 0;`

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-scheduler.h
> +	virtual void Add(Ptr<QuicSocketTxItem> item, bool retx)
same here = 0;

2020-05-18 15:03 UTC, mychele commented on model/quic-socket-tx-scheduler.h
> +	virtual Ptr<QuicSocketTxItem> GetNewSegment(uint32_t numBytes)
same

2020-05-18 17:36 UTC, il-theCrow commented on model/quic-socket-base.cc
> +                   MakeBooleanChecker ())
fixed in 331467b

2020-05-18 17:37 UTC, il-theCrow commented on model/quic-socket-base.cc
> +                   "LegacyCongestionControl",
fixed in 331467b

2020-05-18 17:37 UTC, il-theCrow commented on model/quic-socket-base.cc
> +	.AddAttribute ("CongControl",
fixed in 331467b

2020-05-18 17:37 UTC, il-theCrow commented on model/quic-socket-base.cc
> +				   PointerValue (),
attribute removed in 331467b

2020-05-18 17:46 UTC, il-theCrow commented on model/quic-socket-tx-buffer.h
> +	uint32_t m_priorDelivered { 0 }; //!< The delivered count of the most recent packet delivered
fixed in 331467b

2020-11-13 17:48 UTC, fedech commented
Superceded by new PR

2020-11-13 17:48 UTC, closed without merging